### ISSUE TITLE
`Date();` is not being redefined

### ISSUE THREAD

**Issue by danielfsbarreto** [vesln/timekeeper#24]
Hey there,

I am trying to use **timekeeper** as part of my tool belt for acceptance tests altogether with Rubocop, making sure that both browser and server are in sync. However, I can't make it work. 

The issue I am currently facing is that datepickers on my website are still fetching my real date as the current one. Would that be because timekeeper isn't affecting `Date();`?

![image](https://user-images.githubusercontent.com/4307431/28683193-0fd07230-72d6-11e7-90a8-ba5505c84f5c.png)

Thanks in advance,
Daniel

**Comment by freewil** [comment]
Are the datepickers actually calling `Date()` like that? I would be surprised - because I don't think you are meant to use the Date object like that  - you can do `new Date()` or `Date.now()`.

Are you sure it isn't a timing issue where the datepickers get the current date with `new Date()` or `Date.now()` when the page loads before `timekeeper.freeze()` is called?

**Comment by danielfsbarreto** [comment]
Looks like that's the problem, @freewil. If I wrap my code on `window.onload`, I don't get timekeeper loaded. I will have to investigate more how to do this with chromedriver. Thanks for pointing me to this direction! 🙇

**Comment by danielfsbarreto** [comment]
Not sure if still this `Date();` situation is a problem... I am a js newbie. I will leave up to you whether this issue should be closed or not.
